#!/bin/sh
# dri - shortcut for docker run interactive
# first arg is the image tag/id, second arg is the cmd

args=("$@")

echo docker run -it "${args[0]}" "${args[1]}"

docker run -it "${args[0]}" "${args[1]}"