#!/bin/sh
# gv = git commit local with msg from clipboard / pbpaste 
# git status > git add . > git status > git commit 

tmp=`pbpaste`

echo git commit local: gs ga gs gc 
echo ---

gs

ga

gs

echo git commit -am \'+ $(pbpaste) \'

git commit -am "+ $tmp "

echo commited to repo
echo ---
