#!/bin/sh
# gv = git commit local with msg from clipboard / pbpaste + UTC
# git status > git add . > git status > git commit 

tmp=`pbpaste`
utc=`date +%s`

echo git commit local: gs ga gs gc 
echo ---

gs

ga

gs

echo git commit -am \'$(date +%s) + $(pbpaste) \'

git commit -am "$utc + $tmp "

echo commited to repo
echo ---
