#!/bin/sh
# gv = git commit local with msg from clipboard / pbpaste + UTC
# git status > git add . > git status > git commit + UTCms

tmp=`pbpaste`
utc=`gdate +%s%3N`

echo git commit local: gs ga gs gc 
echo ---

gs

ga

gs

echo git commit -am \'$(gdate +%s%3N) + $(pbpaste) \'

git commit -am "$utc + $tmp "

echo commited to repo
echo ---
