#!/bin/sh
# gx = Most used git command sequence: gs ga gs gc gp
# git status > git add . > git status > git commit > git push

tmp=`pbpaste`

echo Most used git cmd sequence: gs ga gs gc gp

gs

ga

gs

# echo gc \'+ $(pbpaste) \'
echo gc \'+ $tmp \'
gc \'+ $tmp \'

gp