#!/bin/sh
# kr - shortcut for kubectl rollout restart deployment deplName
# first arg is the deplName

args=("$@")

echo kubectl rollout restart deployment "${args[0]}" 

kubectl rollout restart deployment "${args[0]}" 